[package]
name = "vida-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vida-core = { path = "../vida-core" }
tokio.workspace = true
tokio-tungstenite = { version = "0.30", features = ["native-tls"] }
futures-util = "0.3"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
